version: '1'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      HOSTHIS_API_KEY: "zapagnan"
      NEXTAUTH_SECRET: "98E3B2CC28F61492C6934531C828C"
      NEXTAUTH_URL: "http://localhost:3000/"
      GITHUB_ID: "Ov23liNXLmVpxOUT7wMb"
      GITHUB_SECRET: "b555ad0d6d84e9c83b486595be973c5580a50556"
    volumes:
      - .:/app/:delegated
    networks:
      - hosthis-network

networks:
  hosthis-network:
    driver: bridge
    external: true